// <auto-generated />
namespace HospitalProjectNorthYork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class departmentsLocations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(departmentsLocations));
        
        string IMigrationMetadata.Id
        {
            get { return "202303291838026_departmentsLocations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
